[advisories]
version = 2
ignore = [
    { id = "RUSTSEC-2024-0388", reason = "this is an unmaintained transitive subdep of a dev dep" },
    { id = "RUSTSEC-2024-0436", reason = "this is an unmaintained transitive subdep of a dep" },
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"

[licenses]
version = 2
confidence-threshold = 0.9
# copyleft = "deny"
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unlicense",
    "MPL-2.0",
    "CC0-1.0",
    "Unicode-3.0",
    "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
